"""POST /api/admin/demo-refresh — simulate a content refresh.
On Vercel/serverless: returns error (can't persist files).
Local/dev: writes deterministic demo JSON for today.
Requires Authorization: Bearer <ADMIN_TRIGGER_TOKEN>.
"""
from http.server import BaseHTTPRequestHandler
import json, os, datetime, pathlib


def _today_ist():
    ist = datetime.timezone(datetime.timedelta(hours=5, minutes=30))
    return datetime.datetime.now(ist).date().isoformat()


def _demo_section(section_id, section_name, code, n=6):
    items = []
    for i in range(1, n + 1):
        items.append({
            "rank": i,
            "headline": f"Demo headline {i} for {section_name}",
            "summary": f"This is a demo summary for item {i} in the {section_name} section.",
            "source_name": "Demo Source",
            "source_url": f"https://example.com/{section_id}/{i}",
            "credibility_score": 7,
            "why_it_matters": f"Demo insight {i}",
            "peopleos_lens": "Executive perspective placeholder.",
        })
    return {
        "section_id": section_id,
        "section_name": section_name,
        "code": code,
        "section_summary": f"Demo section summary for {section_name}.",
        "items": items,
    }


DEMO_SECTIONS = [
    ("india_stock_market",  "India Stock Market",  "S1"),
    ("us_stock_market",     "US Stock Market",     "S2"),
    ("global_markets",      "Global Markets",      "S3"),
    ("ai_news",             "AI News",             "S4"),
    ("ai_research_papers",  "AI Research Papers",  "S5"),
    ("trending_topics",     "Trending Topics",     "S6"),
    ("hr_news_india",       "HR News India",       "S7"),
    ("global_hr_news",      "Global HR News",      "S8"),
    ("hr_research_papers",  "HR Research Papers",  "S9"),
    ("macroeconomics",      "Macroeconomics",      "S10"),
    ("microeconomics",      "Microeconomics",      "S11"),
    ("major_updates",       "Major Updates",       "S12"),
]


class handler(BaseHTTPRequestHandler):

    def do_OPTIONS(self):
        self.send_response(200)
        self._cors()
        self.end_headers()

    def do_POST(self):
        # Auth check
        auth = self.headers.get('Authorization', '')
        expected = os.environ.get('ADMIN_TRIGGER_TOKEN', '')
        if expected and auth != f'Bearer {expected}':
            self._json({'ok': False, 'error': 'Unauthorized.'}, 401)
            return

        date = _today_ist()
        issues_dir = pathlib.Path('landing/data/issues')
        dates_file = pathlib.Path('landing/data/dates.json')

        # Detect if running on Vercel (read-only filesystem)
        if os.environ.get('VERCEL') or os.environ.get('VERCEL_ENV'):
            self._json({
                'ok': False,
                'mode': 'production',
                'date': date,
                'error': 'Demo refresh cannot persist files on Vercel. Use Trigger Production Refresh to dispatch GitHub Actions.',
            })
            return

        # Local/dev: write demo issue
        try:
            issues_dir.mkdir(parents=True, exist_ok=True)
            sections = [_demo_section(*s) for s in DEMO_SECTIONS]
            total_items = sum(len(s['items']) for s in sections)
            issue = {
                'issue_date': date,
                'title': f'PeopleOS Brief — {date} (DEMO)',
                'subject': f'PeopleOS Brief — {date} Intelligence (DEMO)',
                'preheader': 'Demo issue generated by admin refresh.',
                'executive_summary': 'This is a demo issue generated by the admin simulate refresh button.',
                'total_sections': len(sections),
                'total_dashboard_items': total_items,
                'total_email_items': len(sections) * 2,
                'sections': sections,
                '_demo': True,
            }

            issue_path = issues_dir / f'{date}.json'
            with open(issue_path, 'w', encoding='utf-8') as f:
                json.dump(issue, f, ensure_ascii=False, indent=2)

            # Update dates.json
            existing_dates = []
            if dates_file.exists():
                try:
                    existing_dates = json.loads(dates_file.read_text())['dates']
                except Exception:
                    existing_dates = []
            if date not in existing_dates:
                existing_dates = [date] + existing_dates
            dates_file.write_text(json.dumps({'dates': existing_dates}, indent=2))

            self._json({
                'ok': True,
                'mode': 'local',
                'date': date,
                'message': f'Demo issue created for {date}. Reload / to see it.',
                'total_sections': len(sections),
                'total_items': total_items,
            })
        except Exception as exc:
            self._json({'ok': False, 'error': str(exc)[:300]}, 500)

    def _cors(self):
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type, Authorization')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')

    def _json(self, body, status=200):
        payload = json.dumps(body).encode()
        self.send_response(status)
        self._cors()
        self.send_header('Content-Type', 'application/json')
        self.end_headers()
        self.wfile.write(payload)

    def log_message(self, *args):
        pass


app = handler
application = handler
