"""
PeopleOS Brief — Demo data for local/preview mode.
3 dates × 12 sections × 6 items = 216 article objects.
Realistic, premium content. No lorem ipsum.
"""
from __future__ import annotations
import datetime


def _item(rank, headline, summary, why, lens, action, source_name, source_domain, url, date="2026-05-30", cred=7):
    return {
        "rank": rank,
        "headline": headline,
        "summary": summary,
        "why_it_matters": why,
        "peopleos_lens": lens,
        "action": action,
        "source_name": source_name,
        "source_domain": source_domain,
        "source_url": url,
        "published_date": date,
        "credibility_score": cred,
    }


def _build_sections(date: str, variant: int = 0) -> list[dict]:
    v = variant  # slight variation per date

    s1_items = [
        _item(1, f"Nifty 50 {'gains 0.8%' if v==0 else 'slips 0.4%' if v==1 else 'holds 24,200'} on mixed global cues",
              f"Nifty {'rose to 24,350' if v==0 else 'fell to 23,980' if v==1 else 'consolidated near 24,200'} as FIIs {'bought' if v!=1 else 'sold'} ₹2,100 cr in equities. IT and banking led {'gains' if v!=1 else 'losses'}.",
              "FII flow direction is the primary driver of near-term Nifty trajectory.",
              "Market direction affects hiring budgets, ESOP valuations, and workforce sentiment in listed companies.",
              f"Watch FII net flows daily at NSE data portal.",
              "Economic Times", "economictimes.indiatimes.com", "https://economictimes.indiatimes.com/markets/stocks/market-stats/nifty-sensex-daily-update-2026-05-30/articleshow/demo.cms", date, 8),
        _item(2, f"Sensex {'up 400 pts' if v==0 else 'down 250 pts' if v==1 else 'flat near 80,100'} as RBI holds rates steady",
              "RBI MPC held repo rate at 6.5% in line with expectations. Banking index reacted positively with HDFC Bank up 1.2%.",
              "Rate stability supports credit growth and reduces refinancing risk for corporates.",
              "Stable rates benefit HR budgets through predictable borrowing costs and steady business expansion plans.",
              "Monitor RBI governor's commentary for forward guidance clues.",
              "Moneycontrol", "moneycontrol.com", "https://www.moneycontrol.com/news/business/markets/sensex-nifty-live-rbi-rates-may-2026.html", date, 8),
        _item(3, "IT sector outperforms as Infosys, TCS report deal wins",
              f"Infosys announced ${'1.2' if v==0 else '0.9' if v==1 else '1.5'}B deal win in BFSI vertical. TCS guided for 8-10% revenue growth next quarter.",
              "Large deal wins signal continued enterprise tech spending despite macro uncertainty.",
              "IT hiring sentiment improves with deal inflows — watch for freshers campus hiring revival.",
              "Track Infosys and TCS investor day presentations for workforce guidance.",
              "Business Standard", "business-standard.com", "https://www.business-standard.com/markets/news/it-sector-rally-infosys-tcs-deal-wins-2026-05-30.html", date, 8),
        _item(4, "Midcap index hits 52-week high on domestic liquidity surge",
              "NSE Midcap 150 index hit a record as domestic mutual fund SIP flows crossed ₹21,000 cr monthly for third straight month.",
              "Domestic retail investor participation is now a structural counterbalance to FII volatility.",
              "Strong domestic liquidity supports SME sector growth — relevant for HR leaders in mid-size companies.",
              "Review AMFI monthly SIP data for retail investor sentiment proxy.",
              "Mint", "livemint.com", "https://www.livemint.com/market/stock-market-news/midcap-52-week-high-domestic-liquidity-sip-2026-05-30.html", date, 8),
        _item(5, "Auto stocks rally as EV adoption data shows 40% YoY growth",
              "Passenger EV sales grew 42% YoY in latest month. Tata Motors and M&M gained 2-3% on strong order books.",
              "EV adoption curve is steepening faster than most enterprise planning cycles anticipated.",
              "Auto sector hiring is bifurcating — combustion roles declining, EV and software roles expanding sharply.",
              "Review Society of Indian Automobile Manufacturers monthly sales data.",
              "Financial Express", "financialexpress.com", "https://www.financialexpress.com/auto/industry/ev-adoption-tata-motors-mahindra-sales-data-may-2026/3412345.html", date, 7),
        _item(6, "Pharma index stable as USFDA approvals drive selective gains",
              "Sun Pharma received USFDA approval for a generic cardiovascular drug. Cipla up 1.1% on positive FDA audit outcome.",
              "USFDA approval pipeline is a key valuation driver for Indian pharma exporters.",
              "Pharma sector hiring is expanding in regulatory affairs, clinical research, and quality assurance.",
              "Monitor USFDA enforcement action database for Indian facility risk.",
              "Economic Times Pharma", "economictimes.indiatimes.com", "https://economictimes.indiatimes.com/industry/healthcare/pharma/sun-pharma-usfda-approval-generic-cardiovascular-cipla-audit/articleshow/demo4.cms", date, 7),
    ]

    s2_items = [
        _item(1, f"S&P 500 {'gains 0.6%' if v==0 else 'falls 0.9%' if v==1 else 'holds near 5,300'} ahead of Fed minutes",
              f"S&P 500 {'rose to 5,340' if v==0 else 'fell to 5,240' if v==1 else 'closed at 5,305'}. Nvidia up {'3.2%' if v==0 else '1.1%'} on AI chip demand commentary. Fed minutes due tomorrow.",
              "Fed minutes will determine whether rate-cut expectations get pushed further out.",
              "US market direction signals global risk appetite which flows into India FII behavior.",
              "Read FOMC meeting minutes at federalreserve.gov when released.",
              "Reuters", "reuters.com", "https://www.reuters.com/markets/us/sp500-gains-ahead-fed-minutes-nvidia-surge-2026-05-30/", date, 9),
        _item(2, "Nvidia crosses $3T market cap on data center AI demand",
              "Nvidia's quarterly revenue guidance of $28B exceeded analyst estimates by 15%. Data center segment now 87% of revenue.",
              "Nvidia's dominance signals that AI infrastructure spend is accelerating, not plateauing.",
              "Enterprise AI adoption speed is being gated by GPU availability — a constraint for AI-native operators.",
              "Review Nvidia's earnings call transcript for enterprise AI adoption signals.",
              "CNBC", "cnbc.com", "https://www.cnbc.com/2026/05/30/nvidia-crosses-3-trillion-market-cap-ai-chip-demand.html", date, 9),
        _item(3, "Apple announces AI features in iOS 19 at WWDC",
              "Apple Intelligence expands to on-device AI writing, summarization, and Siri 2.0 with contextual awareness across apps.",
              "On-device AI shifts privacy calculus — enterprises can now deploy AI tools without cloud data concerns.",
              "Apple's AI rollout will accelerate employee AI tool adoption from the bottom up, bypassing IT procurement.",
              "Assess your organization's BYOD AI policy readiness.",
              "The Verge", "theverge.com", "https://www.theverge.com/2026/5/30/apple-intelligence-ios-19-wwdc-siri-2-announcement.html", date, 8),
        _item(4, "Meta Platforms up 2.1% as ad revenue growth accelerates to 22%",
              "Meta Q2 revenue of $42B grew 22% YoY driven by Reels advertising and AI-personalized feed performance.",
              "Meta's ad performance confirms consumer digital attention is consolidating on AI-personalized platforms.",
              "Employer branding and talent acquisition teams need to shift budgets toward AI-personalized ad channels.",
              "Review Meta Business Manager performance metrics for recruitment ad ROI.",
              "MarketWatch", "marketwatch.com", "https://www.marketwatch.com/story/meta-platforms-ad-revenue-growth-22-percent-ai-personalized-2026-05-30", date, 8),
        _item(5, "US 10Y Treasury yield rises to 4.6% on strong jobs data",
              "US non-farm payrolls added 235,000 jobs vs 185,000 expected. 10Y yield spiked 12bps to 4.62%.",
              "Strong labor market data pushes back Fed rate cut expectations to Q4 at earliest.",
              "US rate environment directly affects tech layoff cycles and VC funding available for AI startups.",
              "Track CME FedWatch tool for real-time rate cut probability shifts.",
              "Bloomberg", "bloomberg.com", "https://www.bloomberg.com/news/articles/2026-05-30/us-10y-treasury-yield-4-6-strong-jobs-data-fed-outlook", date, 9),
        _item(6, "Microsoft Azure AI revenue grows 35% as enterprise adoption widens",
              "Microsoft reported Azure grew 35% in AI workloads. Copilot integration now deployed at 60% of Fortune 500.",
              "Microsoft's Copilot penetration at Fortune 500 is the clearest signal of enterprise AI adoption speed.",
              "HR leaders in large enterprises need AI literacy programs to match the Copilot rollout pace.",
              "Review Microsoft's AI Adoption Report for enterprise workforce readiness data.",
              "CNBC", "cnbc.com", "https://www.cnbc.com/2026/05/30/microsoft-azure-ai-35-percent-growth-copilot-fortune-500.html", date, 9),
    ]

    s3_items = [
        _item(1, "Brent crude falls to $78 on OPEC+ output disagreement",
              "OPEC+ meeting ended without agreement on production cuts. Brent crude fell 2.3% to $78.20/barrel.",
              "Oil price weakness reduces input cost pressure for manufacturing-heavy emerging markets including India.",
              "Lower crude benefits India's import bill — positive for INR stability and corporate cost structures.",
              "Monitor OPEC+ press releases for production policy changes.",
              "Reuters", "reuters.com", "https://www.reuters.com/markets/us/sp500-gains-ahead-fed-minutes-nvidia-surge-2026-05-30//commodities", date, 9),
        _item(2, "Euro weakens against dollar as ECB signals cautious rate cuts",
              "EUR/USD fell to 1.072 after ECB president indicated just two rate cuts likely in 2026 vs market's three expected.",
              "Euro weakness signals diverging EU-US growth trajectories with implications for global trade.",
              "Multinationals with EUR revenue need to assess FX hedging strategies for 2026 planning cycles.",
              "Track ECB press conference transcripts for forward guidance language shifts.",
              "Financial Times", "ft.com", "https://www.ft.com/content/brent-crude-opec-plus-output-disagreement-may-2026-article", date, 9),
        _item(3, "China manufacturing PMI contracts for third month, signals slowdown",
              "China's Caixin Manufacturing PMI fell to 48.9, below 50 for third straight month, signaling contraction.",
              "China demand slowdown has downstream effects on commodity prices and Asian supply chains.",
              "India-based manufacturers may benefit from supply chain diversification away from China.",
              "Review monthly China PMI data from Caixin for supply chain risk assessment.",
              "Bloomberg", "bloomberg.com", "https://www.bloomberg.com/news/articles/2026-05-30/china-caixin-pmi-48-9-contraction-third-month-slowdown", date, 9),
        _item(4, "Gold hits $2,400/oz as safe-haven demand rises on geopolitical tension",
              "Gold spot price rose to $2,408 as Middle East tensions escalated and central bank gold buying continued.",
              "Rising gold prices signal elevated geopolitical risk premium being priced into global markets.",
              "Safe-haven rallies historically correlate with hiring freezes and capital preservation mode in MNCs.",
              "Monitor World Gold Council's central bank buying data monthly.",
              "Reuters", "reuters.com", "https://www.reuters.com/markets/us/sp500-gains-ahead-fed-minutes-nvidia-surge-2026-05-30//metals", date, 9),
        _item(5, "Japan Nikkei hits 39,000 on yen weakness and export earnings",
              "Nikkei 225 rose 1.4% to 39,100 as JPY/USD weakened to 157. Japanese exporters reporting strong earnings.",
              "Yen weakness makes Japanese exports competitive but complicates Bank of Japan's normalization path.",
              "Japanese corporate earnings recovery is attracting global talent to Tokyo tech hubs.",
              "Track Bank of Japan rate decisions for yen trajectory signals.",
              "Bloomberg", "bloomberg.com", "https://www.bloomberg.com/news/articles/2026-05-30/nikkei-39000-yen-weakness-export-earnings-bank-of-japan", date, 8),
        _item(6, "UK FTSE 100 resilient at 8,200 despite weak PMI data",
              "FTSE 100 held near record levels despite UK services PMI falling to 51.2. Energy and financial stocks led.",
              "UK market resilience despite weak data signals defensive institutional positioning.",
              "UK's post-Brexit talent market remains tight in financial services and technology sectors.",
              "Review ONS UK labor market data for hiring trend signals.",
              "Financial Times", "ft.com", "https://www.ft.com/content/uk-ftse-100-8200-services-pmi-resilient-may-2026-article", date, 9),
    ]

    s4_items = [
        _item(1, "OpenAI launches GPT-5 with 10x reasoning improvement",
              f"OpenAI released GPT-5 with chain-of-thought reasoning benchmarking {'20%' if v==0 else '18%' if v==1 else '22%'} above GPT-4o on MMLU. API pricing reduced 50%.",
              "GPT-5's reasoning jump makes AI viable for complex knowledge work that GPT-4 struggled with.",
              "HR teams now face a genuine skills obsolescence cycle in analytical and writing-intensive roles.",
              "Run GPT-5 on your top 3 high-cost repetitive workflows today.",
              "OpenAI Blog", "openai.com", "https://openai.com/blog/gpt-5-chain-of-thought-reasoning-launch-2026-05-30", date, 9),
        _item(2, "Google releases Gemini 2.0 Ultra with 1M token context window",
              "Gemini 2.0 Ultra processes up to 1 million tokens, enabling analysis of entire codebases, legal docs, and annual reports.",
              "1M token context removes the document-length barrier that prevented enterprise AI deployment in legal, finance, and HR.",
              "Document-heavy HR workflows — policy reviews, contract analysis, candidate dossiers — are now AI-automatable.",
              "Test Gemini 2.0 Ultra on your longest, most time-consuming document review process.",
              "Google DeepMind", "deepmind.google", "https://deepmind.google/technologies/gemini/ultra-1-million-token-context-window-enterprise-2026/", date, 9),
        _item(3, "Anthropic raises $4B Series E at $45B valuation",
              "Anthropic closed a $4B round led by Amazon with participation from Google. Claude 4 Opus launch imminent.",
              "Anthropic's valuation confirms the frontier AI infrastructure arms race is accelerating.",
              "Enterprise teams betting on Claude for safety-critical AI deployments are backed by significant capitalization.",
              "Review Anthropic's Constitutional AI paper to understand their safety differentiation.",
              "TechCrunch", "techcrunch.com", "https://techcrunch.com/2026/05/30/perplexity-ai-100-million-monthly-users-enterprise-search//2026/05/30/anthropic-raises-4-billion-series-e-45b-valuation/", date, 8),
        _item(4, "EU AI Act enforcement begins — first compliance deadlines hit",
              "The EU AI Act's first enforcement wave begins, requiring companies to register high-risk AI systems. Fines up to €30M.",
              "EU AI Act creates compliance cost for any enterprise deploying AI in hiring, performance, or credit decisions.",
              "HR AI tools used in Europe — including ATS ranking and performance scoring — face immediate audit requirements.",
              "Audit all HR AI tools for EU AI Act compliance tier classification now.",
              "Reuters", "reuters.com", "https://www.reuters.com/technology/artificial-intelligence/eu-ai-act-first-enforcement-high-risk-systems-fines-30m-2026-05-30/", date, 9),
        _item(5, "Microsoft Copilot for HR launches with payroll and performance integration",
              "Microsoft Copilot for HR now integrates with SAP SuccessFactors and Workday, enabling natural language HR data queries.",
              "Natural language HR data access reduces analyst dependency and democratizes people analytics.",
              "HRIS teams need to shift from report generation to insight interpretation as Copilot handles the former.",
              "Pilot Copilot for HR with your people analytics team on 3 recurring reports.",
              "VentureBeat", "venturebeat.com", "https://venturebeat.com/ai/microsoft-copilot-hr-successfactors-workday-integration-2026/", date, 8),
        _item(6, "Meta releases Llama 4 Scout as open-source model, beats GPT-4",
              "Meta's Llama 4 Scout, available open-source, outperforms GPT-4 on coding and reasoning benchmarks.",
              "Open-source model quality parity with closed models changes enterprise AI cost structure dramatically.",
              "Organizations can now run production-grade AI on-premise without per-token API costs.",
              "Evaluate Llama 4 Scout for internal HR chatbot and policy Q&A deployment.",
              "Meta AI", "ai.meta.com", "https://ai.meta.com/blog/llama-4-scout-open-source-gpt4-benchmark-release-2026/", date, 9),
    ]

    s5_items = [
        _item(1, "ArXiv paper: Agents can now plan 100-step tasks without human checkpoints",
              "Paper from Stanford + Google introduces PLAN-AGT framework enabling LLM agents to execute 100+ step plans with self-correction and <5% failure rate.",
              "100-step autonomous agent execution crosses the threshold for real enterprise workflow automation.",
              "HR process automation — onboarding, background checks, policy updates — now feasible with minimal human oversight.",
              "Read PLAN-AGT paper abstract at arxiv.org/abs/2406.XXXX.",
              "arXiv / Stanford", "arxiv.org", "https://arxiv.org/abs/2406.demo0000", date, 9),
        _item(2, "New paper shows LLMs match PhD economists on complex policy analysis",
              "UC Berkeley paper tests GPT-4 class models against PhD economists on 200 policy scenarios. LLMs score within 8% accuracy.",
              "LLMs achieving near-PhD-level policy reasoning accelerates AI deployment in strategy, consulting, and advisory roles.",
              "Knowledge workers in strategic analysis roles need to redefine their value proposition beyond information synthesis.",
              "Download and test the paper's benchmark tasks on your own AI stack.",
              "arXiv / UC Berkeley", "arxiv.org", "https://arxiv.org/abs/2406.demo0000", date, 9),
        _item(3, "Microsoft Research: RAG systems now achieve 94% factual accuracy on enterprise docs",
              "MSR paper introduces HybridRAG combining semantic and structured retrieval. Enterprise doc Q&A accuracy hits 94%.",
              "94% factual accuracy crosses enterprise adoption threshold for knowledge management AI.",
              "HR knowledge bases — policy documents, handbooks, benefits guides — are now viable for AI Q&A deployment.",
              "Pilot HybridRAG on your HR policy document corpus.",
              "Microsoft Research", "microsoft.com", "https://www.microsoft.com/en-us/research/blog/hybridrag-94-percent-factual-accuracy-enterprise-qa/", date, 9),
        _item(4, "Anthropic publishes Constitutional AI v2.0 with improved safety benchmarks",
              "Anthropic's updated Constitutional AI framework reduces harmful output rate by 73% vs v1.0 on adversarial red-teaming.",
              "Improved AI safety benchmarks reduce compliance and reputational risk for enterprise AI deployments.",
              "HR AI tools built on Constitutional AI principles provide stronger audit trail for bias and safety reviews.",
              "Read Anthropic's Constitutional AI v2.0 paper at anthropic.com/research.",
              "Anthropic", "anthropic.com", "https://www.anthropic.com/research/constitutional-ai-v2-safety-benchmarks-reduced-harmful-output", date, 9),
        _item(5, "DeepMind AlphaFold 3 extended to predict protein-drug interactions",
              "AlphaFold 3 now predicts protein-drug binding with 89% accuracy — a 30% improvement over computational baselines.",
              "AlphaFold's extension to drug interactions accelerates pharma R&D timelines by 40%.",
              "Pharma sector AI adoption is creating new demand for ML bioinformatics talent in India and globally.",
              "Review Nature paper on AlphaFold 3 for life sciences AI application scope.",
              "Google DeepMind", "deepmind.google", "https://deepmind.google/research/publications/alphafold3-protein-drug-interaction-89-percent-accuracy/", date, 9),
        _item(6, "New multimodal paper: AI can now read and interpret complex org charts",
              "Paper from CMU shows GPT-4V fine-tuned on org chart data achieves 91% accuracy in hierarchy extraction and reporting-line inference.",
              "AI that reads org structures enables automated workforce analytics at enterprise scale.",
              "People analytics teams can now automate org design analysis, span-of-control reviews, and structure benchmarking.",
              "Test org chart parsing capabilities in your HR analytics toolchain.",
              "arXiv / CMU", "arxiv.org", "https://arxiv.org/abs/2406.demo0000", date, 8),
    ]

    s6_items = [
        _item(1, "Sam Altman's 'AI does your job in 5 years' tweet goes viral",
              "Sam Altman's tweet suggesting AI will do 'most knowledge work' in 5 years generated 2M+ engagements and media coverage globally.",
              "CEO-level AI timeline predictions signal board-level urgency around workforce transformation planning.",
              "HR leaders need a visible, credible AI workforce strategy — not just a policy — before the next all-hands.",
              "Draft your organization's 3-sentence AI workforce transformation position statement.",
              "Twitter/X Trends", "x.com", "https://x.com/sama/status/demo1234567890-ai-job-automation-5-years", date, 6),
        _item(2, "Four-day work week trials show 15% productivity gain in latest UK study",
              "UK 4-Day Week Global study of 200 companies shows 15% productivity improvement and 65% reduction in burnout reports.",
              "Productivity gains from 4-day week are now data-backed across multiple large-scale trials.",
              "HR leaders in India need to form a view on 4-day week as it moves from experiment to policy expectation globally.",
              "Review the 4-Day Week Global 2025 report.",
              "BBC", "bbc.com", "https://www.bbc.com/worklife/article/20260530-four-day-week-15-percent-productivity-uk-study-2026", date, 8),
        _item(3, "Perplexity AI reaches 100M monthly users in 18 months",
              "Perplexity AI hit 100M monthly active users — faster than ChatGPT's early growth curve — driven by enterprise search adoption.",
              "Perplexity's growth signals a structural shift from Google search to AI answer engines.",
              "Knowledge workers are shifting their research workflows — HR teams should track AI search tool adoption rates.",
              "Survey your team on primary search behavior: Google vs AI search engines.",
              "TechCrunch", "techcrunch.com", "https://techcrunch.com/2026/05/30/perplexity-ai-100-million-monthly-users-enterprise-search/", date, 8),
        _item(4, "India surpasses Germany to become world's 3rd largest economy by GDP-PPP",
              "IMF data confirms India's GDP (PPP) has exceeded Germany's, making it the third largest economy globally.",
              "India's economic rise is accelerating foreign investment inflows and expanding the talent opportunity window.",
              "Global HR leaders need India talent strategies — not just India delivery center strategies.",
              "Review IMF World Economic Outlook data table for updated GDP-PPP rankings.",
              "IMF", "imf.org", "https://www.imf.org/en/Publications/WEO/Issues/2026/05/global-growth-forecast-3-2-india-us-strength", date, 9),
        _item(5, "ChatGPT adds real-time voice mode with emotional tone detection",
              "OpenAI's latest ChatGPT update adds real-time voice with emotional tone awareness and conversation memory.",
              "Emotionally-aware AI voice creates new expectations for human-AI interaction in customer and employee-facing tools.",
              "HR technology vendors building on voice AI should audit emotional intelligence claims for accuracy and bias.",
              "Test ChatGPT voice mode on 3 common HR use cases: policy Q&A, coaching simulation, onboarding.",
              "OpenAI", "openai.com", "https://openai.com/blog/chatgpt-real-time-voice-emotional-awareness-memory-2026", date, 9),
        _item(6, "Remote work stabilizes at 28% of US working days — Pew Research",
              "Pew Research 2025 survey shows remote work stabilized at 28% of US working days, down from 40% in 2022 but stable for 18 months.",
              "Remote work has found its equilibrium — hybrid is the permanent norm for knowledge workers.",
              "HR policies still treating hybrid as temporary are misaligned with employee expectations and market reality.",
              "Audit your hybrid work policy — is it written for permanence or temporary exception?",
              "Pew Research", "pewresearch.org", "https://www.pewresearch.org/social-trends/2026/05/30/remote-work-stabilizes-28-percent-hybrid-norm-knowledge-workers/", date, 9),
    ]

    s7_items = [
        _item(1, "Infosys announces 50,000 fresher hiring plan for FY27",
              "Infosys committed to hiring 50,000 freshers in FY27 after two years of subdued campus hiring. TCS and Wipro expected to follow.",
              "Large IT firms restarting fresher hiring signals improved revenue visibility and talent pipeline confidence.",
              "Campus hiring revival will tighten engineering college placement competition — HR teams should engage early.",
              "Check placement season schedules at top IITs and NITs for early-mover advantage.",
              "Economic Times", "economictimes.indiatimes.com", "https://economictimes.indiatimes.com/jobs/infosys-50000-fresher-hiring-fy27-campus-recruitment/articleshow/demo2.cms", date, 8),
        _item(2, "Zomato, Swiggy raise delivery partner compensation by 20% amid gig worker pressure",
              "Both platforms raised delivery partner per-order rates by ₹8-12 following protests and pending gig economy legislation.",
              "India's gig economy regulation is approaching an inflection point — companies are proactively adjusting ahead of law.",
              "HR teams at platform companies need to model gig-to-permanent classification risk under upcoming Social Security Code rules.",
              "Review Ministry of Labour's gig worker registration framework draft.",
              "Mint", "livemint.com", "https://www.livemint.com/companies/zomato-swiggy-delivery-partner-compensation-20-percent-gig-workers/demo.html", date, 8),
        _item(3, "India's unemployment rate drops to 7.2% — CMIE data",
              "Centre for Monitoring Indian Economy data shows urban unemployment falling to 7.2%, lowest since Q4 2022.",
              "Declining unemployment tightens talent availability, particularly in mid-skill roles.",
              "Hiring timelines for mid-senior roles are extending — HR teams should expand sourcing pipelines beyond job boards.",
              "Review CMIE unemployment tracker weekly for early hiring market signals.",
              "Business Standard", "business-standard.com", "https://www.business-standard.com/economy/news/india-unemployment-rate-7-2-percent-cmie-may-2026.html", date, 8),
        _item(4, "Byju's NCLT case sets precedent for startup insolvency employee rights",
              "NCLT ruling in Byju's insolvency case mandates back-salary payment to employees before creditor settlements.",
              "Employee priority in startup insolvency is being strengthened by Indian courts — a structural shift.",
              "HR professionals in venture-backed startups should review employee claim priority in company insolvency planning.",
              "Review the Companies Act Section 53 priority waterfall with your legal team.",
              "Economic Times", "economictimes.indiatimes.com", "https://economictimes.indiatimes.com/tech/tech-bytes/india-semiconductor-mission-tata-micron-2-5-billion-fabs/articleshow/demo3.cms/startups", date, 8),
        _item(5, "India IT sector attrition stabilizes at 11% — NASSCOM report",
              "NASSCOM Q2 2026 report shows annualized IT attrition at 11%, down from 21% peak in 2022. Lateral hiring normalizing.",
              "IT attrition normalization means compensation benchmarking leverage is shifting back to employers.",
              "IT HR teams have a window to renegotiate retention strategies before the next AI-driven demand cycle.",
              "Run a flight risk analysis on your top 20% performers before next appraisal cycle.",
              "NASSCOM", "nasscom.in", "https://nasscom.in/knowledge-center/publications/strategic-review-2026/it-attrition-11-percent-stabilizes", date, 8),
        _item(6, "India enacts mandatory menstrual leave policy for listed companies",
              "Ministry of Labour mandates 2 days paid menstrual leave for female employees in listed companies, effective July 2026.",
              "Mandatory menstrual leave expands DEI obligations and creates compliance, scheduling, and culture considerations.",
              "HR teams need policy updates, manager training, and payroll system changes by July 2026 go-live.",
              "Draft your menstrual leave policy and manager communication plan now.",
              "HR Dive India / ETHRWorld", "ethrworld.com", "https://ethrworld.com/news/india-mandatory-menstrual-leave-policy-listed-companies-july-2026", date, 7),
    ]

    s8_items = [
        _item(1, "Amazon mandates 5-day return-to-office globally from September",
              "Amazon CEO confirmed full 5-day RTO for all corporate employees globally, reversing its hybrid-3 policy.",
              "Amazon's 5-day RTO mandate is the strongest corporate signal yet that hybrid flexibility has limits at scale.",
              "HR leaders facing board pressure to mandate RTO now have Amazon as precedent — but also face retention risk data.",
              "Run a workforce risk model: what % of your high performers prefer hybrid? What's your RTO-exit rate estimate?",
              "Reuters", "reuters.com", "https://www.reuters.com/technology/amazon-mandates-5-day-return-to-office-global-corporate-employees-2026-05-30/", date, 9),
        _item(2, "Global talent shortage hits 10-year high — Manpower Group report",
              "Manpower Group 2025 Talent Shortage Survey shows 75% of employers globally report difficulty filling roles — highest since 2014.",
              "Structural talent shortages mean traditional sourcing models are broken — skills-based hiring is mandatory.",
              "People teams need to shift from role-based to skills-based hiring pipelines or risk extended vacancy cycles.",
              "Benchmark your time-to-fill against Manpower Group's industry data.",
              "Manpower Group", "manpowergroup.com", "https://www.manpowergroup.com/workforce-insights/reports/2025/talent-shortage-75-percent-employers-difficulty-filling-roles", date, 8),
        _item(3, "LinkedIn's 2025 Work Trend Index: AI skills are top 3 hiring criteria at 62% of companies",
              "LinkedIn's survey of 20,000+ hiring managers shows AI proficiency now ranks in top 3 hiring criteria at 62% of companies, up from 22% in 2023.",
              "AI skills screening is becoming table-stakes — candidates without AI proficiency are increasingly screened out.",
              "HR teams need to add AI skills assessment to hiring scorecards before next hiring cycle.",
              "Review your job description templates — do they include AI proficiency requirements?",
              "LinkedIn", "linkedin.com", "https://business.linkedin.com/talent-solutions/resources/future-of-recruiting/2026/ai-skills-top-3-hiring-criteria-62-percent-companies", date, 8),
        _item(4, "UK bans non-compete clauses over 3 months for most workers",
              "UK government enacted legislation limiting non-compete clauses to 3 months, effective January 2027.",
              "UK's non-compete restriction accelerates talent mobility and complicates IP protection strategies.",
              "Multinationals with UK operations need immediate employment contract audit and revision.",
              "Engage employment counsel to audit UK non-compete clauses in current offer letters.",
              "BBC", "bbc.com", "https://www.bbc.com/news/business/2026/uk-non-compete-clauses-ban-3-months-workers-legislation", date, 8),
        _item(5, "Workday reports 45% of enterprise HR workflows now AI-assisted",
              "Workday's annual product report shows 45% of customer HR workflows — including performance reviews, promotions, and job matching — now use AI assistance.",
              "AI-assisted HR workflows at 45% represents a tipping point where non-AI HR processes are becoming the exception.",
              "HR teams not yet using AI-assisted workflow tools are operating at a structural productivity disadvantage.",
              "Audit which of your top 10 HR workflows are still fully manual.",
              "VentureBeat", "venturebeat.com", "https://venturebeat.com/hr-technology/workday-45-percent-enterprise-hr-workflows-ai-assisted-2026/", date, 8),
        _item(6, "BCG: Companies with strong people analytics grow revenue 3x faster",
              "BCG research across 1,200 companies finds those with mature people analytics capabilities grow revenue 3x faster than peers.",
              "People analytics maturity is a leading indicator of business performance — not just an HR efficiency metric.",
              "HR teams need to reframe people analytics as a business growth capability, not a cost center.",
              "Map your people analytics maturity against BCG's 4-stage framework.",
              "BCG", "bcg.com", "https://www.bcg.com/publications/2026/people-analytics-maturity-revenue-3x-faster-1200-companies", date, 9),
    ]

    s9_items = [
        _item(1, "Harvard study: Psychological safety is the #1 predictor of team AI adoption",
              "Harvard Business Review research across 400 teams shows psychological safety predicts successful AI tool adoption better than training investment or tool quality.",
              "Creating psychological safety is now a direct business ROI lever, not just a culture nice-to-have.",
              "Managers who build psychologically safe teams will see faster AI adoption ROI than those focused only on tool procurement.",
              "Add a psychological safety assessment to your next team-level engagement survey.",
              "Harvard Business Review", "hbr.org", "https://hbr.org/2026/05/psychological-safety-number-one-predictor-team-ai-adoption-400-teams", date, 9),
        _item(2, "NBER paper: Remote work reduces promotion rates by 14% for women",
              "National Bureau of Economic Research paper finds remote women workers receive promotions 14% less often than in-office counterparts, even with equal performance ratings.",
              "Remote work is creating a hidden gender pay gap through proximity bias in promotion decisions.",
              "HR leaders need to audit promotion and high-potential identification processes for remote worker bias.",
              "Run a promotion rate analysis segmented by work-location status and gender.",
              "NBER", "nber.org", "https://www.nber.org/papers/w99999-remote-work-reduces-promotion-rates-women-14-percent", date, 9),
        _item(3, "McKinsey: Skills-based organizations fill roles 60% faster",
              "McKinsey research shows organizations that use skills-based hiring fill open roles 60% faster and report 40% higher retention at 1 year.",
              "Skills-based hiring delivers measurable speed and quality improvement over traditional role-fit hiring.",
              "Organizations still using job-title-based hiring models are competing at a structural disadvantage for talent.",
              "Pilot skills-based hiring in your next 5 open roles and track time-to-fill.",
              "McKinsey", "mckinsey.com", "https://www.mckinsey.com/capabilities/people-and-organizational-performance/our-insights/skills-based-organizations-60-percent-faster-hiring-2026", date, 9),
        _item(4, "Deloitte: Employee wellbeing investment yields $3.50 ROI per dollar",
              "Deloitte's 2025 Global Human Capital Trends report quantifies wellbeing investment ROI at $3.50 per dollar through reduced absenteeism, turnover, and healthcare costs.",
              "Wellbeing ROI data shifts the conversation from cost to investment — enabling CFO-level business cases.",
              "HR leaders now have CFO-grade evidence to defend wellbeing program budgets during cost pressures.",
              "Build a wellbeing ROI model using Deloitte's methodology for your next budget review.",
              "Deloitte", "deloitte.com", "https://www2.deloitte.com/global/en/insights/topics/talent/employee-wellbeing-roi-3-50-per-dollar-2025.html", date, 9),
        _item(5, "Stanford paper: Manager quality explains 70% of variance in team performance",
              "Stanford Graduate School of Business research on 5,000 teams shows manager quality explains 70% of team performance variance — far exceeding compensation, tools, or team composition.",
              "Manager quality is the single most leveraged intervention point in organizational performance.",
              "Organizations investing in manager selection and development will outperform those focused on perks and compensation.",
              "Audit your manager promotion criteria — are you promoting on individual performance or people leadership indicators?",
              "Stanford GSB", "gsb.stanford.edu", "https://www.gsb.stanford.edu/insights/manager-quality-70-percent-team-performance-variance-5000-teams", date, 9),
        _item(6, "Wharton study: AI coaching tools improve leadership effectiveness by 28%",
              "Wharton research on AI-assisted coaching tools finds 28% improvement in leadership effectiveness scores at 6 months vs traditional coaching.",
              "AI coaching at scale could democratize leadership development beyond senior executives.",
              "HR leaders can now build high-ROI leadership development programs without the cost constraints of 1:1 executive coaching.",
              "Pilot an AI coaching tool with your first-line manager cohort.",
              "Wharton", "wharton.upenn.edu", "https://knowledge.wharton.upenn.edu/article/ai-coaching-tools-28-percent-leadership-effectiveness-improvement-2026/", date, 9),
    ]

    s10_items = [
        _item(1, "US Fed signals two rate cuts in 2026 as inflation falls to 2.3%",
              "Fed Chair Powell indicated two 25bps rate cuts likely in H2 2026 with CPI at 2.3%, approaching the 2% target.",
              "Rate cut trajectory reduces corporate borrowing costs and supports business expansion and hiring plans.",
              "Lower rates improve startup funding conditions and reduce pressure on PE-backed companies to cut headcount.",
              "Track CME FedWatch tool for real-time rate cut probability shifts.",
              "Federal Reserve", "federalreserve.gov", "https://www.federalreserve.gov/monetarypolicy/fomcminutes20260501.htm", date, 9),
        _item(2, "India GDP grows 7.1% in Q1 FY27, beats IMF forecast",
              "India's CSO released Q1 FY27 GDP growth at 7.1% — above IMF's 6.8% forecast. Services sector at 8.4%.",
              "India's growth outperformance attracts FDI and creates sustained demand for skilled labor.",
              "7%+ GDP growth translates into visible hiring demand across IT, financial services, and consumer sectors.",
              "Review RBI's quarterly Monetary Policy Report for hiring demand sector analysis.",
              "RBI / MOSPI", "rbi.org.in", "https://www.rbi.org.in/scripts/BS_PressReleaseDisplay.aspx?prid=demo-india-gdp-7-1-fy27", date, 9),
        _item(3, "Eurozone enters technical recession with Q2 GDP contraction",
              "Eurozone GDP contracted 0.1% in Q2 following Q1's -0.2%, meeting the technical recession definition.",
              "Eurozone recession reduces global demand and puts pressure on export-dependent economies and MNCs.",
              "MNCs with significant EU revenue should model European hiring freeze scenarios for H2 2026.",
              "Review ECB's Economic Bulletin for recession depth and duration forecasts.",
              "European Central Bank", "ecb.europa.eu", "https://www.ecb.europa.eu/press/pr/date/2026/html/ecb.mp202605-eurozone-recession-technical.en.html", date, 9),
        _item(4, "IMF raises global growth forecast to 3.2% on US and India strength",
              "IMF's updated World Economic Outlook raised 2026 global growth to 3.2%, up from 2.9%, driven by US resilience and India's acceleration.",
              "Global growth upgrade supports corporate investment and reduces recessionary talent risk.",
              "Businesses can plan for growth-mode hiring through 2026 rather than defensive cost-cutting.",
              "Download IMF World Economic Outlook 2026 for sector-specific growth data.",
              "IMF", "imf.org", "https://www.imf.org/en/Publications/WEO/Issues/2026/05/global-growth-forecast-3-2-india-us-strength", date, 9),
        _item(5, "China CPI turns negative for second consecutive month, deflation risk rises",
              "China's CPI fell 0.2% YoY in latest month — second consecutive negative print — raising deflation risk concerns.",
              "China deflation risk creates global demand headwinds and accelerates commodity price softness.",
              "Businesses with significant China operations should stress-test revenue assumptions for a prolonged deflation scenario.",
              "Track China NBS monthly CPI and PPI data for deflation trajectory.",
              "Bloomberg", "bloomberg.com", "https://www.bloomberg.com/news/articles/2026-05-30/china-cpi-deflation-risk-second-consecutive-negative", date, 9),
        _item(6, "RBI issues guidance on AI in financial services risk management",
              "RBI released a consultation paper on AI governance frameworks for banks and NBFCs, requiring explainability and bias testing.",
              "RBI's AI governance framework sets a compliance baseline for fintech and bank AI deployments.",
              "HR teams at financial services firms need to classify HR AI tools under the RBI AI risk framework.",
              "Review RBI's AI consultation paper and assess your fintech AI deployment compliance.",
              "RBI", "rbi.org.in", "https://www.rbi.org.in/scripts/BS_PressReleaseDisplay.aspx?prid=demo-ai-governance-financial-services-consultation", date, 9),
    ]

    s11_items = [
        _item(1, "SaaS pricing model shifts from seat-based to usage-based across enterprise software",
              "Gartner research shows 60% of SaaS enterprise contracts renewing in 2026 are shifting to consumption-based pricing, reducing upfront cost visibility.",
              "Consumption pricing shifts budget risk from vendors to buyers — enterprise CFOs face unpredictable software cost structures.",
              "HR software buyers need to model consumption-based pricing scenarios before renewing HRIS and ATS contracts.",
              "Audit your top 5 HR software contracts for pricing model and renewal terms.",
              "Gartner", "gartner.com", "https://www.gartner.com/en/newsroom/press-releases/2026-05-30-saas-consumption-pricing-60-percent-enterprise-contracts", date, 9),
        _item(2, "Gig economy platform pricing wars depress contractor rates in tech",
              "Upwork and Fiverr report 15-20% decline in average contractor rates over 18 months as AI tools substitute for entry-level freelance work.",
              "AI is creating a labor market deflationary effect on cognitive-commodity freelance work.",
              "Organizations relying on freelance talent for content, data entry, and analysis need workforce cost model updates.",
              "Reassess your contingent workforce cost model for AI substitution risk.",
              "Bloomberg", "bloomberg.com", "https://www.bloomberg.com/news/articles/2026-05-30/gig-economy-contractor-rates-decline-ai-substitution-upwork-fiverr", date, 9),
        _item(3, "Amazon Prime membership pricing power study shows 35% inelasticity",
              "Academic study in Journal of Marketing finds Amazon Prime members show 35% price inelasticity — willing to absorb price increases without cancellation.",
              "Platform subscription loyalty is measurable and actionable — a model for enterprise software vendor strategy.",
              "HR software vendors with embedded workflow dependencies can maintain pricing power despite market competition.",
              "Assess your HRIS switching cost — are you a locked-in buyer or a price-elastic one?",
              "Journal of Marketing", "ama.org", "https://journals.ama.org/doi/10.1177/demo-amazon-prime-price-inelasticity-35-percent-study", date, 7),
        _item(4, "Labor market monopsony in US tech cities widening, MIT study finds",
              "MIT study finds employer concentration in 12 major US tech hubs has increased since 2020, reducing workers' wage negotiation leverage.",
              "Employer monopsony concentration reduces wage growth pressures in tech hubs despite talent shortages.",
              "HR teams in concentrated markets have more pricing power than talent scarcity alone would suggest.",
              "Review local labor market concentration data from NBER papers on your hiring geography.",
              "MIT", "mit.edu", "https://economics.mit.edu/research/publications/2026/labor-market-monopsony-tech-cities-employer-concentration", date, 9),
        _item(5, "Housing affordability crisis accelerating workforce dispersal from tier-1 cities",
              "CBRE research shows housing costs in Mumbai, Delhi, and Bengaluru have outpaced salary growth for 3 consecutive years, accelerating talent migration to tier-2 cities.",
              "Tier-2 city talent pools are becoming viable for roles that previously required relocation to metro areas.",
              "HR teams should expand sourcing to Pune, Hyderabad, Indore, and Kochi for high-quality mid-senior talent.",
              "Run a salary benchmarking analysis for top roles in tier-2 cities vs tier-1 equivalents.",
              "CBRE", "cbre.com", "https://www.cbre.com/insights/reports/2026/india-housing-affordability-tier2-talent-dispersal-mumbai-delhi", date, 8),
        _item(6, "Uber Eats, Zomato pricing algorithms show 22% dynamic surge post-AI optimization",
              "Oxford study of food delivery pricing algorithms shows AI-optimized surge pricing increases average order value by 22% without proportional demand reduction.",
              "AI pricing algorithms are proving more effective than human pricing decisions across consumer platforms.",
              "HR leaders at platform businesses should assess AI pricing tool ROI vs traditional revenue management teams.",
              "Review your company's pricing strategy ownership — is it AI-assisted or still manual?",
              "Oxford Internet Institute", "oii.ox.ac.uk", "https://www.oii.ox.ac.uk/research/publications/2026/ai-pricing-algorithms-surge-22-percent-food-delivery-platforms/", date, 8),
    ]

    s12_items = [
        _item(1, f"India-Canada bilateral trade agreement signed after 12-year negotiations",
              "India and Canada signed the Comprehensive Economic Partnership Agreement covering $100B in annual bilateral trade across services, goods, and professionals.",
              "India-Canada CEPA creates new migration and talent mobility pathways — significant for Indian IT and healthcare workers.",
              "HR teams should assess India-Canada work permit simplification for talent mobility planning.",
              "Review CEPA professional services chapter for visa and credential recognition implications.",
              "Reuters", "reuters.com", "https://www.reuters.com/world/india/india-canada-cepa-trade-agreement-signed-12-year-negotiations-2026-05-30/", date, 9),
        _item(2, "India's UPI crosses 20 billion monthly transactions for the first time",
              "NPCI data shows UPI hit 20.1 billion monthly transactions in May 2026 — a 40% YoY growth — cementing India's position as digital payments leader.",
              "UPI's scale demonstrates India's capability to build world-class financial infrastructure at speed.",
              "Fintech and payments talent demand in India will remain elevated as UPI ecosystem expands globally.",
              "Review NPCI's monthly UPI transaction data dashboard.",
              "NPCI", "npci.org.in", "https://www.npci.org.in/what-we-do/upi/upi-ecosystem-statistics/2026/20-billion-monthly-transactions-may-2026", date, 9),
        _item(3, "G7 agrees on AI governance framework for autonomous weapons ban",
              "G7 nations reached consensus on a framework banning fully autonomous lethal weapons and requiring human oversight of AI in defense.",
              "G7 AI governance signals that international AI regulation is moving from aspiration to binding framework.",
              "Enterprise AI teams should monitor G7 framework language for spill-over into commercial AI regulation.",
              "Review G7 AI governance communiqué for commercial AI policy implications.",
              "Reuters", "reuters.com", "https://www.reuters.com/world/g7-ai-governance-autonomous-weapons-ban-framework-2026-05-30/", date, 9),
        _item(4, "OpenAI's Sora video generation enters enterprise licensing",
              "OpenAI announced Sora enterprise licensing at $500/month for unlimited video generation, targeting marketing and training content.",
              "AI video generation entering enterprise licensing changes content creation economics fundamentally.",
              "L&D and employer branding teams can now produce high-quality training and recruitment videos at near-zero marginal cost.",
              "Pilot Sora for one internal training video module and measure production time savings.",
              "OpenAI", "openai.com", "https://openai.com/blog/sora-enterprise-licensing-500-per-month-video-generation-launch-2026", date, 9),
        _item(5, "India Semiconductor Mission awards $2.5B to Tata and Micron for chip fabs",
              "Government of India awarded ₹20,000 crore subsidies to Tata Semiconductor and Micron for greenfield chip fabrication plants in Gujarat and Assam.",
              "India's semiconductor investment creates a 10-year talent demand pipeline for chip design, fabrication, and testing roles.",
              "Engineering and STEM HR leaders should begin building semiconductor talent pipelines years ahead of fab go-live.",
              "Review India Semiconductor Mission website for talent program partnerships.",
              "Economic Times", "economictimes.indiatimes.com", "https://economictimes.indiatimes.com/tech/tech-bytes/india-semiconductor-mission-tata-micron-2-5-billion-fabs/articleshow/demo3.cms", date, 8),
        _item(6, "WHO declares new mpox variant a global health emergency",
              "WHO declared mpox clade Ib variant a Public Health Emergency of International Concern with confirmed cases in 28 countries.",
              "Global health emergencies create immediate operational risk for businesses with travel-dependent workforces.",
              "HR leaders should update pandemic protocols, travel risk assessments, and remote work continuity plans.",
              "Review your organization's PHEIC response protocol — is it current?",
              "WHO", "who.int", "https://www.who.int/news/item/2026-05-30-mpox-clade-ib-pheic-global-health-emergency-declaration", date, 9),
    ]

    all_sections = [
        {"code": "S1", "section_id": "india_stock_market", "section_name": "India Stock Market",
         "section_summary": f"{'Nifty gains on FII inflows' if v==0 else 'Nifty slips on global cues' if v==1 else 'Nifty consolidates near 24,200'} as RBI holds rates.", "items": s1_items},
        {"code": "S2", "section_id": "us_stock_market", "section_name": "US Stock Market",
         "section_summary": f"{'S&P gains on Nvidia surge' if v==0 else 'S&P falls ahead of Fed' if v==1 else 'S&P holds as Fed minutes loom'}.", "items": s2_items},
        {"code": "S3", "section_id": "global_markets", "section_name": "Global Markets",
         "section_summary": "Crude falls on OPEC+ rift. Euro weakens. China PMI contracts.", "items": s3_items},
        {"code": "S4", "section_id": "ai_news", "section_name": "AI News",
         "section_summary": "GPT-5 launches. Gemini 2.0 hits 1M context. EU AI Act enforcement begins.", "items": s4_items},
        {"code": "S5", "section_id": "ai_research_papers", "section_name": "AI Research Papers",
         "section_summary": "100-step agents, PhD-level policy reasoning, 94% RAG accuracy — key papers this week.", "items": s5_items},
        {"code": "S6", "section_id": "trending_topics", "section_name": "Trending Topics",
         "section_summary": "4-day work week data. Perplexity hits 100M. India becomes 3rd largest economy.", "items": s6_items},
        {"code": "S7", "section_id": "hr_news_india", "section_name": "HR News India",
         "section_summary": "Infosys fresher hiring resumes. Gig worker compensation rises. IT attrition stabilizes.", "items": s7_items},
        {"code": "S8", "section_id": "global_hr_news", "section_name": "Global HR News",
         "section_summary": "Amazon mandates 5-day RTO. Talent shortage hits 10-year high. AI skills now top hiring criteria.", "items": s8_items},
        {"code": "S9", "section_id": "hr_research_papers", "section_name": "HR Research Papers",
         "section_summary": "Psychological safety drives AI adoption. Skills-based hiring 60% faster. Manager quality = 70% of team variance.", "items": s9_items},
        {"code": "S10", "section_id": "macroeconomics", "section_name": "Macroeconomics",
         "section_summary": "Fed signals 2 cuts. India GDP 7.1%. Eurozone enters recession. IMF upgrades global growth.", "items": s10_items},
        {"code": "S11", "section_id": "microeconomics", "section_name": "Microeconomics",
         "section_summary": "SaaS shifts to usage pricing. Gig rates falling on AI substitution. Housing cost pushing talent to tier-2.", "items": s11_items},
        {"code": "S12", "section_id": "major_updates", "section_name": "Major Updates",
         "section_summary": "India-Canada trade deal. UPI crosses 20B transactions. G7 AI governance framework signed.", "items": s12_items},
    ]
    return all_sections


def build_demo_issue(date: str, variant: int = 0) -> dict:
    sections = _build_sections(date, variant)
    total_items = sum(len(s["items"]) for s in sections)
    return {
        "id": f"demo-{date}",
        "issue_date": date,
        "title": f"PeopleOS Brief — {date}",
        "subject": "PeopleOS Brief — Markets, AI, HR & Economy Intelligence",
        "preheader": "12-section daily executive intelligence across markets, AI, HR, and economics.",
        "executive_summary": (
            "Today's brief tracks signals across 12 domains: Indian and US markets show mixed signals as Fed policy uncertainty persists. "
            "GPT-5 and Gemini 2.0 Ultra launch marks a step-change in enterprise AI capability. "
            "India's GDP growth of 7.1% outperforms forecasts while the Eurozone enters recession. "
            "Amazon's 5-day RTO mandate and Harvard's psychological safety research reframe the hybrid work debate."
        ),
        "sections": sections,
        "sources": [],
        "_demo": True,
        "created_at": f"{date}T07:00:00Z",
        "sent_at": f"{date}T07:05:00Z",
        "section_count": len(sections),
        "item_count": total_items,
    }


def get_demo_dates() -> list[str]:
    today = datetime.date.today()
    dates = []
    for i in range(3):
        d = today - datetime.timedelta(days=i)
        dates.append(d.isoformat())
    return dates


def get_demo_issue(date: str | None = None) -> dict:
    dates = get_demo_dates()
    if not date:
        date = dates[0]
    variant = dates.index(date) if date in dates else 0
    return build_demo_issue(date, variant)


def get_demo_archive() -> list[dict]:
    dates = get_demo_dates()
    return [
        {
            "id": f"demo-{d}",
            "issue_date": d,
            "subject": "PeopleOS Brief — Markets, AI, HR & Economy Intelligence",
            "preheader": "12-section daily executive intelligence across markets, AI, HR, and economics.",
            "executive_summary": "Today's brief tracks signals across 12 domains including Indian and global markets, AI news, HR intelligence, and macroeconomics.",
            "section_count": 12,
            "item_count": 72,
            "sent_at": f"{d}T07:05:00Z",
            "_demo": True,
        }
        for d in dates
    ]
